### ISSUE TITLE
Bug Report: Body not properly built for POST actions

### ISSUE THREAD

**Issue by DynamesC** [TaskingAI/TaskingAI#10]
**Describe the bug**
When an assistant intends to trigger an action, the body will not be properly built according to schema if it is a POST action.

**To Reproduce**

1. Create a proper action with POST method.
2. Create an Assistant and grant it the access to the action created in 1. The model applied to assistant should support function calls
3. In Playground, ask the assistant to trigger the action created in 1.

**Expected behavior**
The model successfully received response from the POST endpoint, and generate response based on the response.

**Screenshots**
![WX20240126-153408](https://github.com/TaskingAI/TaskingAI/assets/26886892/a2155d10-9554-4cd4-ad03-aebddce88eea)

**Desktop (please complete the following information):**

- OS: MacOS Monterey 12.5.1
- Browser: Chrome 120.0.6099.109 (Official Build) (arm64)
- Version 0.1.0

**Additional context**

**Comment by DynamesC** [comment]
@jameszyao

**Comment by jameszyao** [comment]
We are now looking into it and will fix asap

**Comment by jameszyao** [comment]
Please refer to README.md and upgrade to the latest docker image version. You can create a new action with your OpenAPI schema and test it again in the playground.

Please give us a confirmation if it works for you now :-)

**Comment by DynamesC** [comment]
Yes it is fixed now. Thanks James.
