### ISSUE TITLE
Looking forward user can define model url for openai model

### ISSUE THREAD

**Issue by elohffa** [TaskingAI/TaskingAI#11]
Is your feature request related to a problem? Please describe.
Yes, currently users are unable to define the model URL for OpenAI models, which limits their flexibility in using custom models.

Describe the solution you'd like
I would like to have the ability to define a custom model URL for OpenAI models. This would allow users to specify their own model URL, enabling them to use custom-trained models or models hosted on different platforms.

Describe alternatives you've considered
One alternative solution could be to provide a configuration option where users can specify the model URL in their code or configuration files. However, having a dedicated parameter or API method specifically for defining the model URL would provide a more straightforward and user-friendly approach.

Additional context
Allowing users to define the model URL would greatly enhance the flexibility and customization options for working with OpenAI models. It would enable users to leverage their own trained models or models hosted on other platforms, expanding the possibilities for various applications and use cases.

Feel free to modify or add more details to the suggested answer based on your specific requirements.

**Comment by jameszyao** [comment]
@elohffa Thanks for your advice. The feature is already on our roadmap and will be added soon. Stay tuned

**Comment by jameszyao** [comment]
@elohffa
 
Please refer to README.md and upgrade to the latest docker image version. You can then find the provider named "Custom Hosting" in the list.

<img width="1359" alt="screenshot" src="https://github.com/TaskingAI/TaskingAI/assets/19534948/c51245e7-fe85-4e8a-b95a-e5e0da80c3d4">

You can refer to OpenAI's API reference to check the difference between function call and tool call architecture.

Please give us a confirmation if it now works for you now :-)

**Comment by jianhai0527** [comment]
<img width="955" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/7888850/e4667c61-74e1-4fae-89ce-1cc3f20f4f65">

how to config self-host.

**Comment by kaixindeyouxia** [comment]
Just like this, add a specified openai URL

![image](https://github.com/TaskingAI/TaskingAI/assets/148513776/c0b9a332-8b29-465d-b22a-92afd9c14c44)

**Comment by jameszyao** [comment]
<img width="1665" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/19534948/7816e48e-c073-43ca-901e-fcc897aa934a">
Custom model integration, following the same API definition as OpenAI, is now available in version 0.1.2 :-)

**Comment by IVTore** [comment]
It simply does not work with LM Studio.
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/88a3edae-ee5e-42c2-acea-9dc188141cd1)
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/30f0f925-06db-4eea-9b6b-ce794cce0117)
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/bf634dc5-1577-424c-ba66-958150b0e80c)
