### ISSUE TITLE
Failed to create "Retrieval" using ollama

### ISSUE THREAD

**Issue by 450220020** [TaskingAI/TaskingAI#112]
**Describe the bug**
Unable to search for ollama when creating "Retrieval", when clicking "Create" it will be the model content for the available items selected by default

**To Reproduce**

1.Click Create Retrivar
2.Search for Olamamoder
3.Found that the created ollama model could not be found
4.Click New, and select ollama in the window inside
5.Ollama's model shows that it is an addition to another model

**Expected behavior**
You should be able to search for models that have already been created, and you should be able to add models correctly when you haven't created them

**Screenshots**
![a](https://github.com/TaskingAI/TaskingAI/assets/52629438/d928203c-7e85-4f3d-9c3b-4ff0373fce8f)
![b](https://github.com/TaskingAI/TaskingAI/assets/52629438/dd31e234-ef8f-4235-91ed-03b435abf913)
![c](https://github.com/TaskingAI/TaskingAI/assets/52629438/a6872610-bdd6-4073-9254-f3336272adef)

**Desktop (please complete the following information):**

**Additional context**

**Comment by DynamesC** [comment]
Thanks for the feedback. We are aware of the issue. It will be fixed with our next release. Please stay tuned.

**Comment by jameszyao** [comment]
By now you can create the embedding model in the Model module directly before creating a retrieval collection
