### ISSUE TITLE
chat_completion function don't work properly

### ISSUE THREAD

**Issue by o3o1** [TaskingAI/TaskingAI#123]
I can create an assistant and chat with it properly, so the model does work well, but can't run the chat_completion function using the example code in the doc:
`chat_completion_result = taskingai.inference.chat_completion(
    model_id=model_id,
    messages=[
        {"role": "system", "content": "You are a health advisor providing nutritional advice. You should always reply with a professional, kind, and patient tone."},
        {"role": "user", "content": "How much suger can a woman take in a day?"},
    ]
)`
Keep getting this error in the picture.
![微信图片_20240523165900](https://github.com/TaskingAI/TaskingAI/assets/71247215/eed1c9b5-a35b-4cb7-9f46-b1a415b4118f)

**Comment by jameszyao** [comment]
@o3o1 Thanks for your feedback. If the chat works in the playgrorund, It seems a client issue. we'll look into it and and provide a quick fix

**Comment by o3o1** [comment]
@jameszyao The UI won't response when confirm model selection in the 'Playground-Chat Completion' interface, but it works fine if you start playground via actions in the 'Models' interface. The function issue seems to occur after I ran a gradio demo, not sure if it's relevant.

**Comment by jameszyao** [comment]
@o3o1 we have released a new client SDK version v0.2.5. Please upgrade your TaskingAI client version using pip and see if the chat completion works now :-)

**Comment by o3o1** [comment]
@jameszyao works fine now, much appreciated :)
