### ISSUE TITLE
When starting the application, there is an error related to connecting to the localhost on port 8002. The specific error is a ConnectionRefusedError with the message [Errno 10061] Connect call failed ('127.0.0.1', 8002).

### ISSUE THREAD

**Issue by luolin-ai** [TaskingAI/TaskingAI#19]
Describe the bug
When starting the application, there is an error related to connecting to the localhost on port 8002. The specific error is a ConnectionRefusedError with the message [Errno 10061] Connect call failed ('127.0.0.1', 8002).

To Reproduce

Start the application.
Observe the error related to connecting to localhost on port 8002.
Expected behavior
The application should start without any connection errors and be able to connect to the specified localhost on port 8002.

Screenshots
![111111111306](https://github.com/TaskingAI/TaskingAI/assets/135555634/9e637001-1933-4c56-8d0c-6c820725bb3c)
![22222220318](https://github.com/TaskingAI/TaskingAI/assets/135555634/8fe8a10a-df5d-49e4-b6c3-141ff7e6feda)

N/A

Desktop (please complete the following information):

OS: Windows (based on the paths in the error log)
Browser: N/A
Version: N/A
Additional context
This error seems to be related to a connection issue with the localhost on port 8002. Further investigation is needed to determine the root cause of the connection problem and resolve it.

**Comment by jameszyao** [comment]
@luolin-ai 
Could you please provide a screenshot of the Docker container status? This can be checked by `docker ps`. Also, could you confirm if you followed the setup instructions below to start the project?

![Installation](https://github.com/TaskingAI/TaskingAI/assets/19534948/b4f3c9e3-9595-4ede-9c83-c202069aa3ae)

**Comment by luolin-ai** [comment]
It is not run directly by Docker code.

**Comment by jameszyao** [comment]
@luolin-ai then another service called taskingai-inference is need. We'll soon make it open-sourced in GitHub. You can run it with docker for now.
`docker pull taskingai/taskingai-inference:latest`

**Comment by luolin-ai** [comment]
OK Thanks. I want to deploy directly through code and make secondary development changes. Looking forward to adding more features
