### ISSUE TITLE
How to customize a text embedding? Or provide an openai proxy configuration？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [TaskingAI/TaskingAI#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
How to customize a text embedding? Or provide an openai proxy configuration？

**Comment by jameszyao** [comment]
@liuhuapiaoyuan  we'll soon enable custom host for text embedding model in next release. Please stay tuned :-)

**Comment by liuhuapiaoyuan** [comment]
Perfect!

**Comment by jameszyao** [comment]
<img width="1617" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/19534948/f285e299-07a4-4112-bea0-e88d1badd0a9">
@liuhuapiaoyuan Custom text embedding model integration, following the same API definition as OpenAI, is now available in version 0.1.2 :-)

**Comment by cleverpig** [comment]
can't support zhipu glm now...
