### ISSUE TITLE
Remove limit for number of chunks that a collection can contain

### ISSUE THREAD

**Issue by racso-dev** [TaskingAI/TaskingAI#224]
**Is your feature request related to a problem? Please describe.**
It's problematic for my usecase to have a limit on the number of chunks that can be uploaded to a collection.

**Describe the solution you'd like**
It would be great to be able to not have a limit on the number of chunks that can be uploaded to a collection. A collection can and should be able to exponentially grow over time.

**Describe alternatives you've considered**
OpenAI doesn't have a limit on the number of docs that can be uploaded to a collection.

(Is there any particular reason as to why that limit exists?)

**Comment by jameszyao** [comment]
@racso-dev thanks for your suggestion. Different chunk limits correspond to different vector index configurations. We'll soon add more capacity options in the next release. Stay tuned :-)
