### ISSUE TITLE
Deployment on a virtual machine ec2, the generate button has no effect

### ISSUE THREAD

**Issue by sharabhshukla** [TaskingAI/TaskingAI#23]
**Describe the bug**
I followed the self-hosting docs, to put it on ec2, using docker compose worked as a charm but once I was in the playground, I send a message on the chat and then when I tried to generate a response, nothing happened. Sometimes it would throw an error "invalid token" other time it wouldnt just react.

I tested the same token and the same steps using docker-compose on my laptop, it works flawless. I know this may not be with the application code but could be with aws.

I was wondering if someone might have some ideas, to debug ?

**To Reproduce**
1. spin a ec2 machine, clone the repo
2. need to adjust the nginx conf, to listen on port 80
3. adjust the docker-compose to match host port 80,  by default it listens on port 8080, in that case need to allow 8080 port to allow inbound connections
4. docker-compose 

**Expected behavior**

**Comment by jameszyao** [comment]
@sharabhshukla  

If the generate button works fine when you turn off debug and stream in the chat settings,  then we can infer the nginx configuration is likely to cause the SSE failure. 

You can try this first to locate the problem and upload the nginx conf file to share more information if needed.

**Comment by sharabhshukla** [comment]
server {
    listen 80;

    location /images/providers/icons/ {
        proxy_pass http://backend-inference:8000;
    }

    location /api/v1/ {
        proxy_pass http://backend-web:8000;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
    }

    location /v1/ {
        proxy_pass http://backend-api:8000;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 24h;
    }

    location / {
        proxy_pass http://frontend:80;
    }
}

**Comment by jameszyao** [comment]
@sharabhshukla Thanks for your information. wWe have located the problem and will allow you to enable streaming on EC2 in next release. Please stay tuned
