### ISSUE TITLE
cannot logoin in with the account and password in the document?

### ISSUE THREAD

**Issue by Oatelauser** [TaskingAI/TaskingAI#26]
I use docker-compose to install Tasking AI, but I cannot log in with the account and password in the document.The login interface keeps getting stuck and the verification cannot be successful.
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/9690d433-95b5-41ad-8738-b3388cfaf8db)

**Comment by jameszyao** [comment]
@Oatelauser Please ensure the backend service is ready. You can use `docker ps` to check the container status.

**Comment by Oatelauser** [comment]
I checked the running status of tasksingai's containers and found that they were all normal.
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/107d6852-026e-48cc-b3fa-8fc6984c4cf2)
When I clicked to log in, I found that the request was not sent and the front-end reported an error and blocked it.
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/bc4d948d-7232-44db-920a-e79c667e0f73)
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/80302161-ac9c-484a-aa71-3d84c433ae35)

**Comment by jameszyao** [comment]
Thanks for providing these. It looks like you are trying to login from another LAN device.

1. Check whether the backend service is ready: `GET http://YOUR_HOST_URL:8080/api/v1/health_check`. If it does not return `{"status":"success"}`, restart docker.
2. Check if login works properly in a localhost environment. If so, check your firewall and security settings.

**Comment by Oatelauser** [comment]
@jameszyao I tried the method you mentioned to troubleshoot the problem, but found several problems：
1.You suspect it is a firewall problem, so I accessed the health check interface on the current machine, and the result was a 500 response.
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/42985088-4673-4617-a8ce-31b5615fc3cb)
2.After I restarted docker, I found that some containers started by docker-compose were not started.
![image](https://github.com/TaskingAI/TaskingAI/assets/149216797/155d55df-1972-4158-b9a6-da4686e11842)

**Comment by jameszyao** [comment]
<img width="537" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/19534948/565cfcb8-034b-49b1-8a35-7a326c3880bc">
As shown in the screenshot above, 7 containers should be started. 
You can use `docker-compose -p taskingai up -d` to start the remaining containers.
