### ISSUE TITLE
Bug in Anthropic Stream Mode with Function Call Handling

### ISSUE THREAD

**Issue by LinkW77** [TaskingAI/TaskingAI#262]
**Describe the bug**

The stream_handle_function_calls function in Anthropic's stream mode is currently only passing and not executing the intended functionality. This issue causes function calls within the stream mode to be ineffective.

**To Reproduce**

1. Set up a request to initialize Anthropic's stream mode.
2. Configure the request to include a function call.
3. Send the request and observe that the stream_handle_function_calls function only passes and does not execute the function call as expected.

**Expected behavior**

The stream_handle_function_calls function should execute the function calls correctly within Anthropic's stream mode, allowing the function to perform its intended operations.

**Desktop (please complete the following information):**

- OS: Windows

**Comment by jameszyao** [comment]
@LinkW77 Thanks we'll look into it and fix asap
