### ISSUE TITLE
Where is repo of taskingai-inference?

### ISSUE THREAD

**Issue by leonlee723** [TaskingAI/TaskingAI#28]
**Describe the bug**
Hi, TaskingAI is a amazing work! I'm deploying the platform via source code on my MacBook. I followed the README, but I found a error. The repo of taskingai-inference link to https://github.com/taskingai/taskingai-inference, but click the URL, you will see a 404 page of Git Hub. The taskingai-inference is a necessary server, so please update the link ASAP. Thanks. 

BTW, doc of your official website (https://docs.tasking.ai/docs/taskingai-inference/overview) has another error about taskingai-inference. In doc page of taskingai-inference, the repo of taskingai-inference link to https://github.com/TaskingAI/Universal-LLM-API. It is another a 404 page of github.

**Comment by jameszyao** [comment]
@leonlee723 thanks for your interest. 
The service is now available to be installed via Docker. We'll aslo make the repo open-source on GitHub very soon.  
Please stay tuned :-)
