### ISSUE TITLE
Integrate OpenAI's New Chat Completion Model (GPT-4o-mini)

### ISSUE THREAD

**Issue by sindre104** [TaskingAI/TaskingAI#284]
**Is your feature request related to a problem? Please describe.**
OpenAI has recently released a new chat completion model named GPT-4o-mini. However, our current system does not support this new model, and we need to make necessary updates to plug it in seamlessly.

**Describe the solution you'd like**
1. Gather detailed information about the GPT-4o-mini model, including its capabilities, limitations, API endpoints, and any specific requirements for integration.
2. Integration Implementation
3. Testing
4. Deployment and Monitoring

**Describe alternatives you've considered**

**Additional context**

**Comment by jameszyao** [comment]
Thanks for your feedback. We'll integrate GPT-4o-mini officially asap. Currently you can use openai-wildcard to use this model in TaskingAI
