### ISSUE TITLE
After filling in the key into the code, it still displays incorrectly.

### ISSUE THREAD

**Issue by luolin-ai** [TaskingAI/TaskingAI#29]
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/549e7416-7a3b-4d64-ac5b-36bdc290252b)

**Comment by jameszyao** [comment]
Thanks for your feedback @luolin-ai 
Can you share some information to help us locate the problem?
1. Your Action OpenAPI Schema
2. Enable debugging mode in the playground and obtain debugging information.

If the info is sensitive to you, please contact support@tasking.ai😀

**Comment by luolin-ai** [comment]
{
    "info": {
        "title": "Tianapi Douyin Hot Trends API",
        "version": "1.0.0",
        "description": "API for retrieving trending topics on Douyin."
    },
    "paths": {
        "/index": {
            "post": {
                "summary": "Get Douyin Hot Trends",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string",
                                            "example": "success"
                                        },
                                        "code": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "result": {
                                            "type": "object",
                                            "properties": {
                                                "list": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "word": {
                                                                "type": "string"
                                                            },
                                                            "label": {
                                                                "type": "integer"
                                                            },
                                                            "hotindex": {
                                                                "type": "integer"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Successful response"
                    }
                },
                "parameters": [
                    {
                        "in": "query",
                        "name": "key",
                        "schema": {
                            "type": "string",
                            "default": "ba145c6b19XXXXX1"
                        },
                        "required": true,
                        "description": "API key for access."
                    }
                ],
                "description": "Posts a request to retrieve a list of trending topics on Douyin.",
                "operationId": "getDouyinHotTrends"
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "https://apis.tianapi.com/douyinhot",
            "description": "Tianapi Douyin Hot Trends Service"
        }
    ]
}

**Comment by luolin-ai** [comment]
{
    "info": {
        "title": "Tianapi Douyin Hot Trends API",
        "version": "1.0.0",
        "description": "API for retrieving trending topics on Douyin."
    },
    "paths": {
        "/index": {
            "post": {
                "summary": "Get Douyin Hot Trends",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string",
                                            "example": "success"
                                        },
                                        "code": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "result": {
                                            "type": "object",
                                            "properties": {
                                                "list": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "word": {
                                                                "type":
"string"
                                                            },
                                                            "label": {
                                                                "type":
"integer"
                                                            },
                                                            "hotindex": {
                                                                "type":
"integer"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Successful response"
                    }
                },
                "parameters": [
                    {
                        "in": "query",
                        "name": "key",
                        "schema": {
                            "type": "string",
                            "default": "ba145c6b19114aef651ccb19daaa84f1"
                        },
                        "required": true,
                        "description": "API key for access."
                    }
                ],
                "description": "Posts a request to retrieve a list of
trending topics on Douyin.",
                "operationId": "getDouyinHotTrends"
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "https://apis.tianapi.com/douyinhot",
            "description": "Tianapi Douyin Hot Trends Service"
        }
    ]
}

James Yao ***@***.***> 于2024年2月6日周二 12:30写道：

**Comment by luolin-ai** [comment]
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/f8394b3c-d2d7-4663-82d7-4219fa94f8f8)

**Comment by luolin-ai** [comment]
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/5adeab0b-a683-4dbb-a557-b56a14fb1d41)

**Comment by luolin-ai** [comment]
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/47be30fb-2946-4423-95a8-3043934e407a)

**Comment by DynamesC** [comment]
Yes the declaration of the 'key' parameter looks good now.

Could you show me your entire updated schema and also the action_input and action_output in the chatting interface (debug mode required)?

> ![image](https://private-user-images.githubusercontent.com/135555634/302547460-5adeab0b-a683-4dbb-a557-b56a14fb1d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDczNTMsIm5iZiI6MTcwNzIwNzA1MywicGF0aCI6Ii8xMzU1NTU2MzQvMzAyNTQ3NDYwLTVhZGVhYjBiLWE2ODMtNGRiYi1hNTU3LWI1NmExNGZiMWQ0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwODEwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjI3MjA3OTViMjg3OGQ0ZTk2NzcyYjdkMjVlNDEyYmYxZWFjYzBlZmM2MWEzYzBkOTZhMTNiNWU1MzQ1ZmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3o0k9csYxPVW-O_-sswVTZODXL0AaDQ7ee2NedOqEP4)

**Comment by luolin-ai** [comment]
{
    "info": {
        "title": "Tianapi Douyin Hot Trends API",
        "version": "1.0.0",
        "description": "API for retrieving trending topics on Douyin."
    },
    "paths": {
        "/index": {
            "post": {
                "summary": "Get Douyin Hot Trends",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "msg": {
                                            "type": "string",
                                            "example": "success"
                                        },
                                        "code": {
                                            "type": "integer",
                                            "example": 200
                                        },
                                        "result": {
                                            "type": "object",
                                            "properties": {
                                                "list": {
                                                    "type": "array",
                                                    "items": {
                                                        "type": "object",
                                                        "properties": {
                                                            "word": {
                                                                "type": "string"
                                                            },
                                                            "label": {
                                                                "type": "integer"
                                                            },
                                                            "hotindex": {
                                                                "type": "integer"
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Successful response"
                    }
                },
                "parameters": [
                    {
                        "in": "query",
                        "name": "key",
                        "schema": {
                            "enum": [
                                "ba145c6b19114aef651ccb19daaa84f1"
                            ],
                            "type": "string"
                        },
                        "required": true,
                        "description": "用于访问的 API 密钥。"
                    }
                ],
                "description": "Posts a request to retrieve a list of trending topics on Douyin.",
                "operationId": "getDouyinHotTrends"
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "https://apis.tianapi.com/douyinhot",
            "description": "Tianapi Douyin Hot Trends Service"
        }
    ]
}

**Comment by luolin-ai** [comment]
Nothing happens when debugging mode is enabled in the playground and messages are sent.

**Comment by luolin-ai** [comment]
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/426086c5-8e64-465f-9db7-a3b22b366a9b)
mo Inexplicably better, thank you

**Comment by DynamesC** [comment]
Great. Usually if the key is in query or in path, fixing it as a enum with only one possible value will solve the problem
