### ISSUE TITLE
Integrate Fireworks AI Models with TaskingAI

### ISSUE THREAD

**Issue by sindre104** [TaskingAI/TaskingAI#297]
**Is your feature request related to a problem? Please describe.**
I think integrating Fireworks AI is a good choice for enhancing TaskingAI. Fireworks AI offers a platform focused on generative AI, emphasizing speed, reliability, and enterprise scalability, while adhering to HIPAA and SOC2 standards.

**Describe the solution you'd like**
I would like to integrate Fireworks AI models into TaskingAI using their inference API. This integration should allow users to access and utilize Fireworks AI models directly within the TaskingAI environment, enabling model fine-tuning and customization for specific requirements. The integration should be seamless and maintain TaskingAI's existing functionality and user experience.

**Additional context**
Fireworks AI specializes in small, open-source models and offers extensive customization options, making it a suitable provider for businesses looking to tailor AI solutions to their unique needs. The integration should ensure that TaskingAI users can utilize these features efficiently.

**Comment by SimsonW** [comment]
Thank you for your suggestion. Fireworks is already supported in the open-source version(please see linked PR), and we will be launching fireworks in the next official release.
