### ISSUE TITLE
Add Support for New Groq AI Models with Function Call Capability

### ISSUE THREAD

**Issue by JonathanChan298** [TaskingAI/TaskingAI#298]
**Is your feature request related to a problem? Please describe.**
The current system does not support the latest Groq AI models and their function call capabilities. This limits our ability to utilize the latest advancements and features provided by Groq.

**Describe the solution you'd like**
1. Research the new AI models offered by Groq.
2. Update the system to support the new Groq models.
3. Implement functionality to utilize function calls with these models.
4. Test the integration thoroughly to ensure compatibility and performance.
5. Update the documentation to reflect the changes.

**Comment by SimsonW** [comment]
Thank you for your suggestion. We have already updated the information for each of the groq models, and the related features will be launched in the next official release.
