### ISSUE TITLE
The v0.3.0 version cannot create an assistant through the console.

### ISSUE THREAD

**Issue by wzs1566** [TaskingAI/TaskingAI#327]
**Describe the bug**

I recently upgraded to version v0.3.0 of taskingai, but I found that the models and Retrieval I created before are still there (visible in the console), yet no assistants are displayed on the frontend (it shows 'No assistant'). More importantly, I am unable to create new assistants (after creation, they are not visible in the console, but SDK calls show that the assistant exists and can be accessed via the API). Which logs do I need to submit?
**To Reproduce**

1.Upgrade from v0.2.2 to v0.3.0
2.This issue occurs intermittently. After upgrading the taskingai project deployed on another machine, I noticed that all Retrievals disappeared. However, through SDK calls, I can still print out the previous Retrievals, but they are not displayed on the frontend.
3.I tried deploying v0.3.0 from scratch using Docker and manually created it. In the absence of historical data, there were no issues.

**Comment by wzs1566** [comment]
![CleanShot 2024-09-13 at 10 59 24@2x](https://github.com/user-attachments/assets/232e692b-653f-4371-83d3-666d421f6740)

![CleanShot 2024-09-13 at 11 38 42@2x](https://github.com/user-attachments/assets/f0da4661-a282-4c16-b9e0-3f673eb5cdb7)


I can use the SDK to print all created Assistants, but the console does not display any assistants.

**Comment by jameszyao** [comment]
@wzs1566 It seems to be a frontend issue. Can you provide more information if there are any errors printed in the browser console?

**Comment by wzs1566** [comment]
When creating an assistant, I checked the container's output logs, and the taskingai-backend-web-1 container produced an error. The log is as follows:

10.42.7.59:33760 - "POST /api/v1/assistants HTTP/1.1" 200
10.42.7.59:33770 - "GET /api/v1/ui/assistants?limit=20 HTTP/1.1" 404
10.42.7.59:33772 - "GET /api/v1/ui/assistants?limit=20 HTTP/1.1" 404
2024-09-14 04:01:48,721 - apscheduler.executors.default - INFO - Running job "sync_data (trigger: interval[0:01:00], next run at: 2024-09-14 04:02:48 UTC)" (scheduled at 2024-09-14 04:01:48.720902+00:00)
2024-09-14 04:01:48,721 - app.fastapi_app - INFO - Syncing model schema data...
2024-09-14 04:01:48,726 - app.fastapi_app - INFO - Syncing plugin data...
2024-09-14 04:01:48,729 - apscheduler.executors.default - INFO - Job "sync_data (trigger: interval[0:01:00], next run at: 2024-09-14 04:02:48 UTC)" executed successfully

**Comment by wzs1566** [comment]
Here is what the browser console printed:
[consoleLOG.txt](https://github.com/user-attachments/files/17001104/consoleLOG.txt)

**Comment by wzs1566** [comment]
Here is what the browser console printed:

```index-vW7hKNZG.js:71 i18next: languageChanged zh-CN
index-vW7hKNZG.js:71 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: Array(1), fallbackLng: Array(1), …}
index-vW7hKNZG.js:69 
        
 GET http://rag.bnuaifn.cn:9080/api/v1/ui/assistants?limit=20 404 (Not Found)
(匿名) @ index-vW7hKNZG.js:69
xhr @ index-vW7hKNZG.js:69
pc @ index-vW7hKNZG.js:71
Promise.then
request @ index-vW7hKNZG.js:71
pi.<computed> @ index-vW7hKNZG.js:71
(匿名) @ index-vW7hKNZG.js:67
(匿名) @ actions-gTvU5UGw.js:1
(匿名) @ index-vW7hKNZG.js:79
(匿名) @ index-i6EnDKD9.js:1
Ri @ index-vW7hKNZG.js:40
_n @ index-vW7hKNZG.js:40
bu @ index-vW7hKNZG.js:40
Kt @ index-vW7hKNZG.js:38
tg @ index-vW7hKNZG.js:40
qt @ index-vW7hKNZG.js:40
Ff @ index-vW7hKNZG.js:40
k @ index-vW7hKNZG.js:25
te @ index-vW7hKNZG.js:25
index-vW7hKNZG.js:71 D {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}code: "ERR_BAD_REQUEST"config: adapter: Array(2)0: "xhr"1: "http"length: 2[[Prototype]]: Array(0)baseURL: "/"data: undefinedenv: {FormData: ƒ, Blob: ƒ}headers: bi {Accept: 'application/json, text/plain, */*', Content-Type: null, Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdW…xMjl9.OUco43RY0jPMzu0eldQ7H_-_ilnFoB2n5hBLThwKWhU'}maxBodyLength: -1maxContentLength: -1method: "get"timeout: 60000transformRequest: [ƒ]transformResponse: [ƒ]transitional: {silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}url: "api/v1/ui/assistants?limit=20"validateStatus: ƒ (t)xsrfCookieName: "XSRF-TOKEN"xsrfHeaderName: "X-XSRF-TOKEN"[[Prototype]]: Objectmessage: "Request failed with status code 404"name: "AxiosError"request: XMLHttpRequestonabort: ƒ ()onerror: ƒ ()onload: nullonloadend: ƒ v()onloadstart: nullonprogress: nullonreadystatechange: nullontimeout: ƒ ()readyState: 4response: "{\"status\":\"error\",\"error\":{\"code\":\"OBJECT_NOT_FOUND\",\"message\":\"collection DbgYlxtyrfvoodauwcvjcf64 not found\"}}"responseText: "{\"status\":\"error\",\"error\":{\"code\":\"OBJECT_NOT_FOUND\",\"message\":\"collection DbgYlxtyrfvoodauwcvjcf64 not found\"}}"responseType: ""responseURL: "http://rag.bnuaifn.cn:9080/api/v1/ui/assistants?limit=20"responseXML: nullstatus: 404statusText: "Not Found"timeout: 60000upload: XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}withCredentials: false[[Prototype]]: XMLHttpRequestresponse: config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 60000, …}data: {status: 'error', error: {…}}headers: bi {connection: 'keep-alive', content-length: '112', content-type: 'application/json', date: 'Sat, 14 Sep 2024 04:24:54 GMT', server: 'nginx/1.21.5'}request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 60000, withCredentials: false, upload: XMLHttpRequestUpload, …}status: 404statusText: "Not Found"[[Prototype]]: Objectstack: "AxiosError: Request failed with status code 404\n    at jv (http://rag.bnuaifn.cn:9080/assets/index-vW7hKNZG.js:69:1042)\n    at XMLHttpRequest.v (http://rag.bnuaifn.cn:9080/assets/index-vW7hKNZG.js:69:4231)"[[Prototype]]: Errorconstructor: ƒ D(e,t,n,r,o)toJSON: ƒ ()isAxiosError: true[[Prototype]]: Object
index-yC45ZJUi.js:1
