### ISSUE TITLE
How to build TaskingAI on personal computers develop environment?

### ISSUE THREAD

**Issue by BaoBao112233** [TaskingAI/TaskingAI#335]
**Is your feature request related to any problem? Please describe.**
I would like to run TaskingAI on my local machine without using Docker. Could you provide detailed instructions on how to set it up manually, including environment setup, dependencies, and any additional configuration required?

**Environment:**
Operating System: Ubuntu 20.04
Python version: 3.10.12
TaskingAI Version: lastest version

**What I've tried so far:**
Cloned the repository.
Installed Python dependencies using pip install -r requirements.txt.
Tried to configure the environment variables manua

**Describe the solution you want**
I don't want to use Docker, I want to use it on my own personal computer.

**Comment by jameszyao** [comment]
Please set up Python env for the backend according to /backend/requirements.txt and React + Typescript env for the frontend
