### ISSUE TITLE
You can add openrouter.ai

### ISSUE THREAD

**Issue by seoeaa** [TaskingAI/TaskingAI#34]
You can add https://openrouter.ai/

**Comment by jameszyao** [comment]
@seoeaa Thanks for the suggestion. We'll look into it.

**Comment by prxshetty** [comment]
openrouter.ai is not explicitly an LLM. also I think openrouter could confuse users.I don't see any clear benefits of adding them. Or you can create them on your own without integrating them into this.
Just a suggestion.

**Comment by jiacheo** [comment]
I don't think integrating openrouter is valueless because many enterprise purchase openrouter as their uniform LLM backends. AWS Bedrock, Groq and Hugging Face Inference API are also not explicitly LLMs.
