### ISSUE TITLE
A tip about docker upgrades and static volumes

### ISSUE THREAD

**Issue by IVTore** [TaskingAI/TaskingAI#37]
A tip about docker upgrades and static volumes.
Hi, 
I observed that your docker compose file generates static volumes intrinsic to docker file system.
This may seem to be advantageus for "it runs on my computer" problems.
But in my experience it may cause trouble during upgrades (not your code upgrade).
In rare cases of docker upgrades, docker may mess up the internal docker file system.
I lived through three such events.
I would advise you to carry these volumes to host file system, at best to the directory of installation like ./database etc.
Thanks for your interest.

**Comment by jameszyao** [comment]
@IVTore Thank you for constructive feedback. We'll take it into consideration and improve the deploy process.
