### ISSUE TITLE
REQUEST_VALIDATION_ERROR

### ISSUE THREAD

**Issue by YangZhiBoGreenHand** [TaskingAI/TaskingAI#40]
requestBody why Param type object is not supported.

**Comment by IVTore** [comment]
Until this gets resolved, the project is in a useless state for me.

**Comment by jameszyao** [comment]
@IVTore @YangZhiBoGreenHand Can you please provider more context about this issue? e.g. error message or screenshots thanks

**Comment by IVTore** [comment]
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/757215f8-6d78-4f0b-a40e-f7ce0dec20ee)
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/b18171cb-fbb1-4431-98a1-1ada97329e58)
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/63113f19-7163-4b9c-b587-02055356e2d5)
![image](https://github.com/TaskingAI/TaskingAI/assets/29803458/14e16aed-d0f1-48ee-8af2-18889ca040bb)

**Comment by IVTore** [comment]
Attn: also a typo. Fucntion call. -> Function call I guess.

**Comment by YangZhiBoGreenHand** [comment]
@jameszyao when support array and object
<img width="1020" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/105403828/646fddba-911d-4ad0-b955-a781631749ba">
