### ISSUE TITLE
Model type is required for wildcard models

### ISSUE THREAD

**Issue by Opswatch** [TaskingAI/TaskingAI#49]
**Describe the bug**
When running in docker and we try to add a wildcard based model we get the error Model type is required for wildcard models

**To Reproduce**

1. Stand up docker stack
2. Try to add any wildcard based model

**Expected behavior**
Expect the model to be added 

**Desktop (please complete the following information):**

- OS: Windows 11 running on wsl2
- Browser [e.g. chrome, safari] Tried both firefox and chrome

**Additional context**
 Running the latest taskingai docker stack

**Comment by jameszyao** [comment]
@Opswatch Thanks for your feedback, and we are also handling this and will officially release v0.2.0 very soon. Please stay tuned.
