### ISSUE TITLE
Please a better understandable doc for LM Studio.

### ISSUE THREAD

**Issue by IVTore** [TaskingAI/TaskingAI#58]
The common use for local llm and tasking ai is as follows mostly:
Local LLM server : Directly on OS. (because installing docker NVidia drivers are a burden). 
TaskingAI : Docker. (because it is easy).
So please in your documentation state this at the TOP, 
or maybe in the UI state the examples of LM Studio Addresses like:
```
"If TaskingAI is on docker, address should be 
  http://host.docker.internal:<your port>
  otherwise
  http://localhost:<your port>"
```
This seems ok so far it is working. But let me ask you another question:
IF I use a non docker version of TaskingAI, and give the address
```
http://localhost:<your port>
```
Will it connect? Since TaskingAI is trying to force https (TLS) ?

**Comment by DynamesC** [comment]
Thanks for the recommendation IVTore.  

Yes given the current conditions, the most common combination of TaskingAI and LM Studio is to run LM Studio on OS and TaskingAI on Docker. And this requires to specify the address like `http://host.docker.internal:<your port>`. This information is included in the documentation at the bottom of [Integrating with LM Studio](https://docs.tasking.ai/docs/integration/models/language_models/lm-studio). It seems we didn't give this information enough exposure, and that caused your confusion, and we are sorry for that. We will highlight this at proper positions later.

Another thing we need to clarify is that we are not forcing to use https. So the answer to your last question is YES, it will connect.

**Comment by IVTore** [comment]
Thank you for your kind answer.

**Comment by DynamesC** [comment]
In the latest update of the docs, the information is pined to the top of each page of local models. I'm closing this issue.

Thanks again for the feedback!
