### ISSUE TITLE
Ollama support and support for Nomic Embedding.

### ISSUE THREAD

**Issue by Mayorc1978** [TaskingAI/TaskingAI#59]
**Is your feature request related to a problem? Please describe.**
Support for nomic Embedding. Considering it's pretty fast and accurate and recently included in Ollama, support would be a good alternative to other embedding models already there.

**Describe the solution you'd like**
Integrate nomic embedding models.

**Comment by jameszyao** [comment]
👌 Sure, we'll try to include this in the next version

**Comment by Photize** [comment]
I added the   nomic-embed-text:latest  LLM  to ollama and in the taskingai models , its a very small embeding model , then I set up embedding reteieval and it work fine straight out of the box ! I hope this helps 
![image](https://github.com/TaskingAI/TaskingAI/assets/146000583/65ff99d0-abad-4393-9dea-f057c165b43c)
