### ISSUE TITLE
Custom model API service interface

### ISSUE THREAD

**Issue by tom54007** [TaskingAI/TaskingAI#62]
How to customize the model service API?
For example, how to modify openai's base_url?

**Comment by jameszyao** [comment]
Hi @tom54007, have you checked the provider "custom_host"? Does this meet your requirements
Related Docs: https://docs.tasking.ai/docs/integration/models/language_models/custom-host

**Comment by jmgb27** [comment]
I am also looking on changing the openai's base_url. It is possible with the custom_host, BUT my proxy needs custom headers so custom_host does not fit my use case.

**Comment by jameszyao** [comment]
> I am also looking on changing the openai's base_url. It is possible with the custom_host, BUT my proxy needs custom headers so custom_host does not fit my use case.
Gotcha, then we'll try to design a mechanism to allow custom headers. please stay tuned :-)

**Comment by tom54007** [comment]
Thank you very much. After fit in this [project(one-api)](https://github.com/songquanpeng/one-api), it completely solved my needs.
