### ISSUE TITLE
docker compose: can not change the default password.

### ISSUE THREAD

**Issue by daawen** [TaskingAI/TaskingAI#64]
i changed the default password, but it's not working, i can still login with the old password.

docker-compose.yml file:

  backend-web:
    image: taskingai/taskingai-server:v0.2.1
    environment:
      POSTGRES_URL: postgres://postgres:TaskingAI321@db:5432/taskingai
      REDIS_URL: redis://:TaskingAI321@cache:6379/0
      TASKINGAI_INFERENCE_URL: http://backend-inference:8000
      TASKINGAI_PLUGIN_URL: http://backend-plugin:8000
      AES_ENCRYPTION_KEY: b90e4648ad699c3bdf62c0860e09eb9efc098ee75f215bf750847ae19d41e4b0 # replace with your own
      JWT_SECRET_KEY: dbefe42f34473990a3fa903a6a3283acdc3a910beb1ae271a6463ffa5a926bfb # replace with your own
      PURPOSE: WEB
      DEFAULT_ADMIN_USERNAME: admin
      DEFAULT_ADMIN_PASSWORD: TaskingAI3210 # replace with your own

**Comment by jameszyao** [comment]
@daawen Please make sure to set a different DEFAULT_ADMIN_PASSWORD the first time you start the docker container

**Comment by daawen** [comment]
is it stored in the database POSTGRES?
how can i change the password if i not set at the first time?
thanks.
