### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError

### ISSUE THREAD

**Issue by victory458537** [TaskingAI/TaskingAI#65]
**Describe the bug**
When I run taskingai, this aiohttp.client_exceptions.ClientConnectorError appears. How to solve it?

**To Reproduce**

1.
![image](https://github.com/TaskingAI/TaskingAI/assets/144669640/386afdfb-c691-41b2-8bd6-1aac5486d168)

2.
3.
4.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jameszyao** [comment]
@victory458537 Please make sure you have set up TaskingAI-Inference and TaskingAI-Plugin Docker pods, then specify them in the environment variables:

e.g.
TASKINGAI_INFERENCE_URL: http://localhost:8001
TASKINGAI_PLUGIN_URL: http://localhost:8002
