### ISSUE TITLE
introduce an option to split the text based on specific characters or symbols like ‘/n’

### ISSUE THREAD

**Issue by wzs1566** [TaskingAI/TaskingAI#67]
**Describe the solution you'd like**
I would like to suggest an enhancement to the text_splitter feature. Currently, it only allows splitting text based on a specified chunk_size. However, it would be beneficial if we could introduce an option to split the text based on specific characters or symbols, such as '/n' for newline.

This additional functionality would enable users to directly upload standardized documents for automatic creation of records. By leveraging newline or other suitable characters as delimiters, the text would be segmented more accurately, aligning with the structure of the original document.

Implementing this feature would streamline the process of creating records from structured documents, enhancing the overall user experience and efficiency.

Thank you for considering this suggestion. I appreciate your efforts in continuously improving the product.

Best regards,

**Comment by jameszyao** [comment]
@wzs1566 Thanks for your advice, it's a reasonable way to split the content. we'll add a new splitter to implement the feature
