### ISSUE TITLE
is that so

### ISSUE THREAD

**Issue by luolin-ai** [TaskingAI/TaskingAI#79]
is that so
![image](https://github.com/TaskingAI/TaskingAI/assets/135555634/34888c7d-5f7d-49a0-80ce-f6fa769212cc)

_Originally posted by @luolin-ai in https://github.com/TaskingAI/TaskingAI/issues/77#issuecomment-2024670688_

**Comment by jameszyao** [comment]
we'll discuss this topic in #77
