### ISSUE TITLE
Now admin resource permissions are all, if I want to have multiple users, how should I do and design resource isolation between users

### ISSUE THREAD

**Issue by YangZhiBoGreenHand** [TaskingAI/TaskingAI#81]
if I want to have multiple users, how should I do and design resource isolation between users

**Comment by jameszyao** [comment]
TaskingAI adopts the concept of BaaS (Backend as a Service) and focuses on providing a user-friendly agent runtime and APIs. 

When using the community version, currently you can manage your users in a client service; we plan to allow team member management in the [cloud version](https://app.tasking.ai), it's also a good choice if you are interested in serverless hosting
