### ISSUE TITLE
chat completion stream JSONDecodeError

### ISSUE THREAD

**Issue by YangZhiBoGreenHand** [TaskingAI/TaskingAI#82]
At the end of the question, you will definitely report this JSONDecodeError

**Comment by YangZhiBoGreenHand** [comment]
<img width="601" alt="image" src="https://github.com/TaskingAI/TaskingAI/assets/105403828/1b694569-859e-4a2b-a993-94d6694bdd81">

**Comment by jameszyao** [comment]
Thanks for your feedback. This will be fixed in our next release :-)
